// Keywords configuration for Solar Installation - SEO URL slugs

export interface KeywordConfig {
  slug: string;
  title: string;
  h1: string;
  metaDescription: string;
  description: string;
  keywords: string[];
}

// Solar Installation Keywords - matching actual page folders
export const solarKeywords: KeywordConfig[] = [
  // Capacity Based (kW systems)
  { slug: "1kw-solar-system-price-vadodara", title: "1kW Solar System Price Vadodara 2026 | ₹45,000 Only", h1: "1kW Solar System Price in Vadodara – Starting ₹45,000", metaDescription: "🌞 1kW solar system at just ₹45,000 in Vadodara! Perfect for small homes (100-150 units/month). Includes installation + 25-year warranty. Get ₹30,000 subsidy. Call now!", description: "Get best 1kW solar system price in Vadodara starting from ₹45,000. Perfect for small homes with 100-150 units monthly consumption.", keywords: ["1kW solar price vadodara", "1kW solar system cost", "small solar system vadodara", "1kw rooftop solar"] },
  
  { slug: "2kw-solar-system-price-vadodara", title: "2kW Solar System Price Vadodara | ₹60,000 Subsidy", h1: "2kW Solar System Price in Vadodara – Get ₹60,000 Subsidy", metaDescription: "⚡ 2kW solar at best price in Vadodara! Ideal for 2BHK (200-250 units). ₹60,000 govt subsidy + 25-year warranty. Reduce bills by 80%. Free survey!", description: "2kW solar system price in Vadodara with subsidy. Ideal for homes with 200-250 units monthly consumption.", keywords: ["2kW solar price vadodara", "2kW solar system cost", "2BHK solar system", "2kw solar panel price"] },
  
  { slug: "3kw-solar-system-price-vadodara", title: "3kW Solar System Price Vadodara | ₹78,000 Max Subsidy", h1: "3kW Solar System Price in Vadodara – Maximum ₹78,000 Subsidy", metaDescription: "🔥 BEST VALUE! 3kW solar in Vadodara = ₹78,000 maximum subsidy. Powers 3BHK easily (300-400 units). Zero bills possible! 25-year warranty. Book free survey!", description: "3kW solar system price in Vadodara. Ideal for medium homes with 300-400 units monthly electricity bill.", keywords: ["3kW solar price vadodara", "3kW solar system cost", "3BHK solar", "best home solar system"] },
  
  { slug: "5kw-solar-system-price-vadodara", title: "5kW Solar System Price Vadodara | For Large Homes", h1: "5kW Solar System Price in Vadodara – Large Home Solution", metaDescription: "🏠 5kW solar for villas & bungalows in Vadodara. Generates 600-700 units/month. Complete energy independence! ₹78,000 subsidy + 25-year warranty. Get quote!", description: "5kW solar system price in Vadodara. Best for large homes with 500-600 units monthly consumption.", keywords: ["5kW solar price vadodara", "5kW solar system", "villa solar system", "bungalow solar vadodara"] },
  
  { slug: "10kw-solar-system-price-vadodara", title: "10kW Solar System Price Vadodara | Villa & Commercial", h1: "10kW Solar System Price in Vadodara – Villa & Small Business", metaDescription: "💪 10kW solar powerhouse for large villas & shops in Vadodara. 1200-1400 units generation! Perfect ROI in 4-5 years. Net metering enabled. Get custom quote!", description: "10kW solar system price in Vadodara. For villas, bungalows & small commercial establishments.", keywords: ["10kW solar price vadodara", "10kW solar system", "large solar system", "commercial solar 10kw"] },

  // Solar Panel Types
  { slug: "solar-panels-vadodara", title: "Best Solar Panels in Vadodara | Tata, Waaree, Adani", h1: "Best Solar Panels in Vadodara – Top Brands Available", metaDescription: "🏆 Premium solar panels in Vadodara – Waaree, Tata, Adani, Loom! Mono PERC, Bifacial & Poly options. 25-year warranty, BIS certified. Compare prices & buy!", description: "Best solar panels in Vadodara. Top brands like Adani, Tata, Waaree & Loom Solar available with installation.", keywords: ["solar panels vadodara", "best solar panels", "tata solar panel", "waaree solar vadodara"] },
  
  { slug: "solar-panel-price-vadodara", title: "Solar Panel Price Vadodara 2026 | Latest Rates", h1: "Solar Panel Price in Vadodara 2026 – Complete Price List", metaDescription: "📊 Updated solar panel prices in Vadodara! 1kW: ₹45K | 3kW: ₹1.1L | 5kW: ₹2L (after subsidy). Compare brands & get best deal. Free consultation!", description: "Latest solar panel prices in Vadodara. Compare prices with subsidy benefits. Starting from ₹45,000 for 1kW.", keywords: ["solar panel price vadodara", "solar system price", "solar cost vadodara", "solar rate vadodara"] },
  
  { slug: "bifacial-solar-panel-vadodara", title: "Bifacial Solar Panels Vadodara | 20% More Power", h1: "Bifacial Solar Panels in Vadodara – 20% Extra Generation", metaDescription: "⚡ Bifacial solar panels generate 15-20% MORE power! Both sides capture sunlight. Ideal for limited roof space in Vadodara. Premium efficiency, best ROI!", description: "High-efficiency bifacial solar panels in Vadodara. 10-20% more power generation than standard panels.", keywords: ["bifacial solar panel vadodara", "double sided solar", "high efficiency solar panel", "premium solar"] },
  
  { slug: "polycrystalline-solar-panel-vadodara", title: "Polycrystalline Solar Panels Vadodara | Budget Friendly", h1: "Polycrystalline Solar Panels in Vadodara – Affordable Choice", metaDescription: "💰 Budget solar panels in Vadodara! Polycrystalline panels at ₹20-24/watt. Reliable 20-year performance. Best value for money. Subsidy available!", description: "Affordable polycrystalline solar panels in Vadodara. Best value for money with reliable performance.", keywords: ["polycrystalline solar panel", "poly solar vadodara", "budget solar panel", "affordable solar"] },
  
  { slug: "mono-perc-solar-panel-vadodara", title: "Mono PERC Solar Panels Vadodara | Highest Efficiency", h1: "Mono PERC Solar Panels in Vadodara – Maximum Efficiency", metaDescription: "🏆 Mono PERC = Highest efficiency solar! 20-22% efficiency, generates more in less space. Premium choice for Vadodara homes. 25-year performance warranty!", description: "Premium Mono PERC solar panels in Vadodara. Highest efficiency panels with 25-year warranty.", keywords: ["mono perc solar vadodara", "monocrystalline panel", "high efficiency solar", "premium solar panel"] },

  // System Types
  { slug: "rooftop-solar-vadodara", title: "Rooftop Solar Installation Vadodara | 90% Bill Savings", h1: "Rooftop Solar Installation in Vadodara – Save 90% on Bills", metaDescription: "🏠 Turn your roof into a money-saver! Rooftop solar in Vadodara with 90% bill reduction. ₹78,000 subsidy, net metering, 25-year warranty. Free roof assessment!", description: "Rooftop solar installation in Vadodara. Save up to 90% on electricity bills with solar rooftop systems.", keywords: ["rooftop solar vadodara", "roof solar installation", "rooftop solar system", "solar on roof"] },
  
  { slug: "on-grid-solar-system-vadodara", title: "On-Grid Solar System Vadodara | Sell Power to UGVCL", h1: "On-Grid Solar System in Vadodara – Net Metering Enabled", metaDescription: "💵 On-grid solar = SELL excess power to UGVCL! Best ROI, lowest cost, ₹78,000 subsidy eligible. Net metering credits on your bill. Most popular choice!", description: "On-grid solar system in Vadodara. Net metering enabled, sell excess power to UGVCL.", keywords: ["on grid solar vadodara", "grid tied solar", "net metering solar", "UGVCL solar connection"] },
  
  { slug: "off-grid-solar-system-vadodara", title: "Off-Grid Solar System Vadodara | 24/7 Power Independence", h1: "Off-Grid Solar System in Vadodara – Complete Independence", metaDescription: "🔋 No grid? No problem! Off-grid solar with battery backup in Vadodara. 24/7 power, complete independence. Perfect for farmhouses & remote areas!", description: "Off-grid solar system in Vadodara. 24x7 power backup with batteries, no grid dependency.", keywords: ["off grid solar vadodara", "standalone solar", "battery solar system", "solar without grid"] },
  
  { slug: "hybrid-solar-system-vadodara", title: "Hybrid Solar System Vadodara | Grid + Battery Backup", h1: "Hybrid Solar System in Vadodara – Best of Both Worlds", metaDescription: "⚡ Hybrid solar = Grid benefits + battery backup! Never face power cuts again. Net metering + emergency power in Vadodara. Smart energy solution!", description: "Hybrid solar system in Vadodara. Grid-tied with battery backup for uninterrupted power.", keywords: ["hybrid solar vadodara", "solar with battery", "grid tied with backup", "smart solar system"] },
  
  { slug: "solar-system-for-home-vadodara", title: "Solar System for Home Vadodara | Reduce Bills 90%", h1: "Solar System for Home in Vadodara – 90% Bill Reduction", metaDescription: "🏡 Home solar system in Vadodara starting ₹45,000! Reduce electricity bills by 90%. ₹78,000 subsidy, 25-year warranty. Join 5000+ happy families!", description: "Complete solar system for home in Vadodara. Reduce electricity bills by 90% with residential solar.", keywords: ["solar for home vadodara", "home solar system", "residential solar", "house solar installation"] },

  // Commercial & Industrial
  { slug: "residential-solar-vadodara", title: "Residential Solar Vadodara | ₹78,000 Subsidy for Homes", h1: "Residential Solar Installation in Vadodara – Home Solutions", metaDescription: "🏠 Residential solar experts in Vadodara! On-grid, off-grid & hybrid options. ₹78,000 PM Surya Ghar subsidy. Power your home with clean energy!", description: "Residential solar solutions in Vadodara. On-grid, off-grid & hybrid solar for homes with subsidy.", keywords: ["residential solar vadodara", "home solar installation", "solar for residence", "domestic solar"] },
  
  { slug: "commercial-solar-vadodara", title: "Commercial Solar Vadodara | Cut Business Power Costs", h1: "Commercial Solar Installation in Vadodara – Business Solutions", metaDescription: "🏢 Slash your business electricity costs! Commercial solar in Vadodara for shops, offices, factories. Quick ROI, tax benefits, net metering. Get quote!", description: "Commercial solar installation in Vadodara. Reduce operational costs for businesses with solar energy.", keywords: ["commercial solar vadodara", "business solar", "shop solar", "office solar installation"] },
  
  { slug: "industrial-solar-vadodara", title: "Industrial Solar Vadodara | Large Scale Power Plants", h1: "Industrial Solar Installation in Vadodara – Factory Solutions", metaDescription: "🏭 Industrial solar power plants in Vadodara! 50kW-1MW systems for factories. Massive cost savings, 80% depreciation benefit. EPC solutions available!", description: "Industrial solar installation in Vadodara. Large scale solar for manufacturing units & industrial complexes.", keywords: ["industrial solar vadodara", "factory solar", "manufacturing solar", "large solar plant"] },

  // Subsidy & Government
  { slug: "solar-subsidy-vadodara", title: "Solar Subsidy Vadodara 2026 | Get ₹78,000 Govt Benefit", h1: "Solar Subsidy in Vadodara 2026 – Claim ₹78,000 Benefit", metaDescription: "💰 Don't miss ₹78,000 solar subsidy in Vadodara! PM Surya Ghar scheme 2026. We handle complete paperwork. Limited period offer. Apply today!", description: "Get up to ₹78,000 solar subsidy in Vadodara under PM Surya Ghar scheme. Complete subsidy assistance.", keywords: ["solar subsidy vadodara", "government solar scheme", "PM Surya Ghar subsidy", "MNRE subsidy"] },
  
  { slug: "pm-surya-ghar-vadodara", title: "PM Surya Ghar Vadodara | Free Electricity Scheme 2026", h1: "PM Surya Ghar Yojana in Vadodara – Free Bijli Scheme", metaDescription: "🌞 PM Surya Ghar Muft Bijli Yojana Vadodara! Get 300 units FREE electricity + ₹78,000 subsidy. We handle complete application. Limited slots!", description: "PM Surya Ghar free electricity scheme in Vadodara. Get 300 units free with rooftop solar installation.", keywords: ["PM Surya Ghar vadodara", "muft bijli yojana", "free solar scheme", "government solar yojana"] },
  
  { slug: "solar-net-metering-vadodara", title: "Solar Net Metering Vadodara | Earn from Excess Power", h1: "Solar Net Metering in Vadodara – UGVCL Connection", metaDescription: "💵 Earn money from your rooftop! Net metering in Vadodara lets you sell excess solar power to UGVCL. Get credits on your bill. Complete setup assistance!", description: "Net metering for solar in Vadodara. Export excess power & get credits on your electricity bill.", keywords: ["net metering vadodara", "UGVCL net metering", "solar export", "sell solar power"] },

  // Solar Products
  { slug: "solar-inverter-vadodara", title: "Best Solar Inverters Vadodara | On-Grid & Hybrid", h1: "Best Solar Inverters in Vadodara – All Types Available", metaDescription: "⚡ Top solar inverters in Vadodara – Growatt, Fronius, Havells, Delta! On-grid, off-grid & hybrid options. 5-10 year warranty. Best prices guaranteed!", description: "Best solar inverters in Vadodara. On-grid, off-grid & hybrid inverters from top brands.", keywords: ["solar inverter vadodara", "on grid inverter", "hybrid inverter", "best solar inverter"] },
  
  { slug: "solar-battery-vadodara", title: "Solar Battery Vadodara | Lithium & Tubular Options", h1: "Solar Battery in Vadodara – Power Backup Solutions", metaDescription: "🔋 Solar batteries for backup in Vadodara! Lithium-ion (10+ years) & Tubular options. Never face power cuts. Hybrid system compatible. Compare prices!", description: "Solar battery for backup in Vadodara. Lithium-ion & tubular batteries for solar systems.", keywords: ["solar battery vadodara", "lithium solar battery", "tubular battery solar", "solar backup"] },
  
  { slug: "solar-water-heater-vadodara", title: "Solar Water Heater Vadodara | Cut Geyser Bills 100%", h1: "Solar Water Heater in Vadodara – Zero Electricity Hot Water", metaDescription: "🚿 Hot water FREE forever! Solar water heater in Vadodara. 100-300 LPD capacity. Save ₹2000+/month on geyser bills. 5-year warranty!", description: "Solar water heater installation in Vadodara. Save on electricity with solar geyser systems.", keywords: ["solar water heater vadodara", "solar geyser", "solar hot water", "ETC water heater"] },
  
  { slug: "solar-water-pump-vadodara", title: "Solar Water Pump Vadodara | 90% Subsidy for Farmers", h1: "Solar Water Pump in Vadodara – Agriculture Solutions", metaDescription: "👨‍🌾 Farmers! Get solar pump with 90% govt subsidy in Vadodara. 1HP to 10HP pumps. Free irrigation forever. PM-KUSUM scheme. Apply now!", description: "Solar water pump in Vadodara for agriculture & domestic use. Government subsidy available.", keywords: ["solar water pump vadodara", "agriculture solar pump", "PM KUSUM pump", "solar irrigation"] },
  
  { slug: "solar-ac-vadodara", title: "Solar AC Vadodara | Run AC on Solar Power", h1: "Solar Air Conditioner in Vadodara – Cool Without Bills", metaDescription: "❄️ Run AC on solar in Vadodara! Solar-powered air conditioners & solar system for existing AC. Beat the heat without high bills!", description: "Solar AC & solar powered air conditioners in Vadodara. Run AC on solar power.", keywords: ["solar AC vadodara", "solar air conditioner", "AC on solar", "solar cooling"] },
  
  { slug: "solar-street-light-vadodara", title: "Solar Street Light Vadodara | Society & Garden Lights", h1: "Solar Street Light in Vadodara – Outdoor Lighting", metaDescription: "💡 Solar street lights for societies, gardens & streets in Vadodara. No wiring, no bills! 12-40W LED options. Automatic dusk-to-dawn. Bulk orders welcome!", description: "Solar street light installation in Vadodara. LED solar lights for streets, gardens & societies.", keywords: ["solar street light vadodara", "solar LED light", "garden solar light", "society solar light"] },

  // Services
  { slug: "solar-cleaning-vadodara", title: "Solar Panel Cleaning Vadodara | Boost Output 25%", h1: "Solar Panel Cleaning Services in Vadodara – Increase Efficiency", metaDescription: "🧹 Dirty panels = 25% power loss! Professional solar cleaning in Vadodara. Restore peak performance. AMC plans available. Book cleaning today!", description: "Professional solar panel cleaning in Vadodara. Increase power generation by up to 25%.", keywords: ["solar panel cleaning vadodara", "solar cleaning service", "panel washing", "solar maintenance"] },
  
  { slug: "solar-repair-vadodara", title: "Solar Panel Repair Vadodara | Expert Technicians", h1: "Solar Panel Repair Services in Vadodara – Quick Fix", metaDescription: "🔧 Solar not working? Expert repair in Vadodara! Inverter, panel & wiring issues fixed fast. All brands serviced. Same-day response!", description: "Solar panel & inverter repair services in Vadodara. Quick diagnosis and repair by experts.", keywords: ["solar panel repair vadodara", "solar repair service", "inverter repair", "solar troubleshooting"] },
  
  { slug: "solar-maintenance-vadodara", title: "Solar Maintenance Vadodara | AMC Plans Available", h1: "Solar Panel Maintenance in Vadodara – Keep Peak Performance", metaDescription: "🛠️ Solar AMC & maintenance in Vadodara. Keep your system running at 100%! Annual plans from ₹2000. Cleaning + inspection + repairs included!", description: "Solar panel maintenance & AMC services in Vadodara. Keep your solar system running at peak efficiency.", keywords: ["solar maintenance vadodara", "solar AMC", "solar service plan", "annual maintenance"] },
  
  { slug: "solar-installation-near-me-vadodara", title: "Solar Installation Near Me Vadodara | Local Experts", h1: "Solar Installation Near Me in Vadodara – Quick Service", metaDescription: "📍 Looking for solar installation near you in Vadodara? Local experts, same-day site visit, fast installation. Serving all areas. Call now!", description: "Find the best solar installation near you in Vadodara. Local solar installer with quick service.", keywords: ["solar installation near me", "solar near me vadodara", "local solar installer", "nearby solar company"] },

  // Company & Business
  { slug: "best-solar-company-vadodara", title: "Best Solar Company Vadodara | 5000+ Installations", h1: "Best Solar Company in Vadodara – 5000+ Happy Customers", metaDescription: "🏆 Vadodara's #1 solar company! 5000+ installations, 4.9★ rating, MNRE approved. 25-year warranty, best prices, govt subsidy assistance. Trusted since 2015!", description: "Top rated solar company in Vadodara. 25 year warranty, best prices & professional installation.", keywords: ["best solar company vadodara", "top solar company", "trusted solar installer", "#1 solar vadodara"] },
  
  { slug: "best-solar-installer-vadodara", title: "Best Solar Installer Vadodara | MNRE Approved", h1: "Best Solar Installer in Vadodara – Government Approved", metaDescription: "✅ MNRE & GEDA approved solar installer in Vadodara! 5000+ installations, expert team, quality guaranteed. We handle subsidy paperwork. Book now!", description: "Best solar panel installer in Vadodara. MNRE & GEDA approved with 5000+ installations.", keywords: ["best solar installer vadodara", "MNRE approved installer", "GEDA certified", "expert solar installer"] },
  
  { slug: "top-solar-company-vadodara", title: "Top Solar Company Vadodara | Award Winning Service", h1: "Top Solar Company in Vadodara – Industry Leaders", metaDescription: "🌟 Top-rated solar company in Vadodara! Quality installation + govt subsidy + 25-year warranty. Chosen by 5000+ families. Free consultation!", description: "Top rated solar company in Vadodara. Quality solar installation with government subsidy.", keywords: ["top solar company vadodara", "leading solar installer", "best solar service", "premium solar company"] },
  
  { slug: "solar-consultant-vadodara", title: "Solar Consultant Vadodara | Free Expert Advice", h1: "Solar Energy Consultant in Vadodara – Expert Guidance", metaDescription: "💡 Confused about solar? Free expert consultation in Vadodara! We analyze your needs, roof, bills & recommend perfect system. No obligation!", description: "Expert solar consultant in Vadodara. Free consultation for residential & commercial solar projects.", keywords: ["solar consultant vadodara", "solar advisor", "solar expert", "free solar consultation"] },
  
  { slug: "solar-epc-company-vadodara", title: "Solar EPC Company Vadodara | Complete Solutions", h1: "Solar EPC Company in Vadodara – End-to-End Service", metaDescription: "🏗️ Complete solar EPC in Vadodara – Engineering, Procurement, Construction. Turnkey projects for residential, commercial & industrial. One partner, zero hassle!", description: "Complete solar EPC services in Vadodara. Engineering, procurement & construction - all under one roof.", keywords: ["solar EPC vadodara", "turnkey solar", "solar engineering", "complete solar solution"] },
  
  { slug: "solar-panel-dealer-vadodara", title: "Solar Panel Dealer Vadodara | Authorized Distributor", h1: "Solar Panel Dealer in Vadodara – Genuine Products", metaDescription: "✅ Authorized solar panel dealer in Vadodara! Genuine Tata, Waaree, Adani panels. Best prices, full warranty. Bulk & retail available!", description: "Authorized solar panel dealer in Vadodara. Genuine panels from top brands at best prices.", keywords: ["solar panel dealer vadodara", "authorized dealer", "solar distributor", "genuine solar panels"] },
  
  { slug: "solar-panel-distributor-vadodara", title: "Solar Panel Distributor Vadodara | Wholesale Prices", h1: "Solar Panel Distributor in Vadodara – Bulk Supply", metaDescription: "📦 Solar panel wholesale in Vadodara! Bulk supply for installers & contractors. All major brands. Competitive distributor pricing. Quick delivery!", description: "Wholesale solar panel distributor in Vadodara. Bulk supply for installers & contractors.", keywords: ["solar distributor vadodara", "wholesale solar", "bulk solar panels", "solar supplier"] },
  
  { slug: "solar-panel-manufacturer-vadodara", title: "Solar Panel Manufacturer Near Vadodara | Made in India", h1: "Solar Panel Manufacturer in Vadodara – Indian Brands", metaDescription: "🇮🇳 Made in India solar panels! Top manufacturers near Vadodara – Waaree (Surat), Adani (Mundra). BIS certified, 25-year warranty. Support local!", description: "Solar panel manufacturers in Vadodara. Made in India solar panels with BIS certification.", keywords: ["solar manufacturer vadodara", "made in india solar", "indian solar panels", "BIS certified solar"] },

  // Financing
  { slug: "solar-financing-vadodara", title: "Solar Financing Vadodara | Easy Loans Available", h1: "Solar Financing Options in Vadodara – Easy Approval", metaDescription: "💳 Can't pay upfront? Solar financing in Vadodara! Bank loans, NBFC options, 0% down payment schemes. Easy EMI, quick approval. Go solar today!", description: "Easy solar financing in Vadodara. Zero down payment & low EMI options available.", keywords: ["solar financing vadodara", "solar loan", "solar EMI option", "solar finance scheme"] },
  
  { slug: "solar-emi-vadodara", title: "Solar on EMI Vadodara | ₹2000/Month Onwards", h1: "Solar on EMI in Vadodara – Affordable Monthly Payments", metaDescription: "📱 Solar EMI starting ₹2000/month in Vadodara! No cost EMI options available. Pay as you save on electricity. Easy approval, quick installation!", description: "Get solar on easy EMI in Vadodara. No cost EMI & low interest solar loans available.", keywords: ["solar EMI vadodara", "monthly solar payment", "no cost EMI solar", "affordable solar"] },
  
  { slug: "affordable-solar-vadodara", title: "Affordable Solar Vadodara | Quality at Best Price", h1: "Affordable Solar Installation in Vadodara – Budget Friendly", metaDescription: "💰 Affordable doesn't mean compromise! Quality solar at best prices in Vadodara. ₹78,000 subsidy makes it even cheaper. Compare quotes free!", description: "Affordable solar installation in Vadodara. Quality solar at best prices with subsidy.", keywords: ["affordable solar vadodara", "cheap solar", "budget solar system", "low cost solar"] },
  
  { slug: "cheap-solar-panel-vadodara", title: "Cheap Solar Panels Vadodara | Don't Compromise Quality", h1: "Cheap Solar Panels in Vadodara – Value for Money", metaDescription: "⚠️ Cheap ≠ Low quality! Budget solar panels in Vadodara with full warranty & performance guarantee. Compare tier-1 panels at best prices!", description: "Cheap solar panels in Vadodara without compromising quality. Best value for money.", keywords: ["cheap solar panel vadodara", "budget solar panel", "low cost solar panel", "economical solar"] },
  
  { slug: "zero-electricity-bill-vadodara", title: "Zero Electricity Bill Vadodara | It's Possible!", h1: "Zero Electricity Bill with Solar in Vadodara – Make It Reality", metaDescription: "😱 ₹0 electricity bill is REAL! Join 1000+ Vadodara homes with zero bills. Right-sized solar system + net metering = no more UGVCL payments!", description: "Get zero electricity bill in Vadodara with rooftop solar. Save up to 90% on power bills.", keywords: ["zero electricity bill vadodara", "no power bill", "free electricity", "eliminate light bill"] },
  
  { slug: "solar-panel-installation-cost-vadodara", title: "Solar Installation Cost Vadodara 2026 | Full Breakdown", h1: "Solar Panel Installation Cost in Vadodara – Complete Details", metaDescription: "📊 Transparent solar costs in Vadodara! 1kW: ₹45K, 3kW: ₹1.1L, 5kW: ₹2L (after subsidy). Includes panels, inverter, installation. No hidden charges!", description: "Complete solar panel installation cost breakdown in Vadodara. Know exact pricing with subsidy.", keywords: ["solar installation cost vadodara", "solar panel cost", "solar price breakdown", "solar system cost"] },

  // Environment & Energy
  { slug: "green-energy-vadodara", title: "Green Energy Solutions Vadodara | Go Sustainable", h1: "Green Energy Solutions in Vadodara – Join the Movement", metaDescription: "🌱 Go green with solar in Vadodara! Reduce carbon footprint, save money, help environment. Clean energy for your home & business. Make the switch!", description: "Go green with solar energy in Vadodara. Sustainable & eco-friendly power solutions.", keywords: ["green energy vadodara", "sustainable energy", "eco friendly power", "clean energy"] },
  
  { slug: "renewable-energy-vadodara", title: "Renewable Energy Vadodara | Solar Power Future", h1: "Renewable Energy Solutions in Vadodara – Invest in Future", metaDescription: "♻️ Renewable energy = smart investment! Solar power in Vadodara with 25-year returns. Clean, sustainable, profitable. Future-proof your energy!", description: "Renewable energy solutions in Vadodara. Solar power for clean & sustainable future.", keywords: ["renewable energy vadodara", "clean energy", "sustainable power", "future energy"] },

  // Additional Services
  { slug: "solar-panel-installation-services-vadodara", title: "Solar Installation Services Vadodara | Professional Team", h1: "Solar Panel Installation Services in Vadodara – Expert Team", metaDescription: "👷 Professional solar installation in Vadodara! Trained team, safety compliant, quick installation. We handle everything – survey to subsidy. Book now!", description: "Professional solar panel installation services in Vadodara. Expert team, quality panels & government subsidy assistance.", keywords: ["solar installation services vadodara", "professional installer", "solar setup service", "expert solar team"] },

  // Brand Keywords
  { slug: "tata-solar-panel-vadodara", title: "Tata Solar Panel Vadodara | Authorized Dealer", h1: "Tata Solar Panel Dealer in Vadodara – Trusted Brand", metaDescription: "🏆 Tata Solar panels in Vadodara! Authorized dealer with full warranty. Tata brand trust + solar savings. Installation included. Get Tata quote!", description: "Buy Tata Solar panels in Vadodara with installation. Authorized Tata Power Solar dealer with warranty & subsidy.", keywords: ["tata solar panel vadodara", "tata power solar", "tata solar dealer", "tata solar price"] },
  
  { slug: "waaree-solar-panel-vadodara", title: "Waaree Solar Panel Vadodara | India's Largest", h1: "Waaree Solar Panel Dealer in Vadodara – #1 Indian Brand", metaDescription: "🇮🇳 Waaree = India's LARGEST solar manufacturer! Available in Vadodara with installation. Gujarat-made quality, 25-year warranty. Best for local service!", description: "Waaree solar panels in Vadodara. India's largest solar manufacturer. Buy with installation & 25-year warranty.", keywords: ["waaree solar vadodara", "waaree panel price", "waaree dealer", "waaree solar gujarat"] },
  
  { slug: "adani-solar-panel-vadodara", title: "Adani Solar Panel Vadodara | Premium Quality", h1: "Adani Solar Panel Dealer in Vadodara – Premium Panels", metaDescription: "⭐ Adani Solar panels – Premium Made in India quality! Available in Vadodara. High efficiency, 25-year warranty. Gujarat's pride. Get Adani quote!", description: "Adani Solar panels in Vadodara. Premium quality Made in India panels with 25-year performance warranty.", keywords: ["adani solar vadodara", "adani solar panel", "adani dealer", "premium solar panel"] },
  
  { slug: "loom-solar-vadodara", title: "Loom Solar Vadodara | Shark Tank Fame", h1: "Loom Solar Dealer in Vadodara – Popular Choice", metaDescription: "🦈 Loom Solar (Shark Tank fame) in Vadodara! Mono PERC panels, AC modules available. Great for homes. Modern solar solutions. Get Loom quote!", description: "Loom Solar panels & products in Vadodara. Authorized dealer for Loom Solar mono PERC panels & inverters.", keywords: ["loom solar vadodara", "loom solar panel", "loom dealer", "shark tank solar"] },

  // Use Case Keywords
  { slug: "solar-for-bungalow-vadodara", title: "Solar for Bungalow Vadodara | 5-15kW Systems", h1: "Solar Installation for Bungalow in Vadodara – Premium Solutions", metaDescription: "🏡 Bungalow owners! 5-15kW solar systems for large homes in Vadodara. Complete energy independence, premium aesthetics. ₹78,000 subsidy applicable!", description: "Solar installation for bungalows in Vadodara. 5kW to 15kW systems for independent houses. Get government subsidy.", keywords: ["solar for bungalow vadodara", "bungalow solar system", "large home solar", "independent house solar"] },
  
  { slug: "solar-for-flat-vadodara", title: "Solar for Flat Vadodara | Apartment Solutions", h1: "Solar Installation for Flat in Vadodara – Apartment Options", metaDescription: "🏢 Flat owners can go solar too! Balcony panels, society rooftop sharing in Vadodara. Even 1kW makes a difference. Explore apartment solar options!", description: "Solar for apartments & flats in Vadodara. Balcony solar panels & rooftop sharing solutions for flat owners.", keywords: ["solar for flat vadodara", "apartment solar", "balcony solar panel", "society solar sharing"] },
  
  { slug: "solar-for-villa-vadodara", title: "Solar for Villa Vadodara | Luxury Home Solutions", h1: "Solar Installation for Villa in Vadodara – Premium Living", metaDescription: "🏰 Villa solar in Vadodara – 8-20kW premium systems. Hybrid with battery for zero interruption. Aesthetic installation, complete automation. Luxury meets sustainability!", description: "Premium solar installation for villas in Vadodara. 8kW to 20kW systems with battery backup for luxury homes.", keywords: ["solar for villa vadodara", "villa solar system", "luxury home solar", "premium solar installation"] },
  
  { slug: "solar-for-society-vadodara", title: "Solar for Society Vadodara | 80% Common Area Savings", h1: "Solar for Housing Society in Vadodara – Community Power", metaDescription: "🏘️ Housing societies save 80% on common area bills! Solar for apartments & societies in Vadodara. Lift, pump, lighting – all on solar. Bulk discounts!", description: "Solar for housing societies in Vadodara. Reduce common area electricity bills by 80% with rooftop solar.", keywords: ["solar for society vadodara", "housing society solar", "apartment complex solar", "community solar"] },
  
  { slug: "solar-for-hospital-vadodara", title: "Solar for Hospital Vadodara | 24/7 Reliable Power", h1: "Solar Installation for Hospital in Vadodara – Critical Power", metaDescription: "🏥 Hospitals need reliable power! Hybrid solar systems for healthcare in Vadodara. Zero power cuts, reduced bills. Critical care deserves solar backup!", description: "Solar power for hospitals in Vadodara. 24x7 power backup with hybrid solar systems for healthcare facilities.", keywords: ["solar for hospital vadodara", "hospital solar system", "healthcare solar", "medical facility solar"] },
  
  { slug: "solar-for-school-vadodara", title: "Solar for School Vadodara | Educate & Save", h1: "Solar Installation for School in Vadodara – Educational Institutions", metaDescription: "🏫 Schools going solar in Vadodara! Reduce electricity costs, teach sustainability. Special schemes for educational institutions. Knowledge + savings!", description: "Solar for schools & colleges in Vadodara. Reduce electricity costs for educational institutions with government benefits.", keywords: ["solar for school vadodara", "school solar system", "college solar", "education solar"] },
  
  { slug: "solar-for-farm-vadodara", title: "Solar for Farm Vadodara | 90% Govt Subsidy", h1: "Solar for Agriculture & Farm in Vadodara – Farmer Benefits", metaDescription: "👨‍🌾 Farmers get 90% subsidy! Solar pumps, fencing, cold storage in Vadodara. PM-KUSUM scheme benefits. Free irrigation for life. Apply now!", description: "Solar for farms in Vadodara. Solar pumps, fencing & farm automation with 90% government subsidy.", keywords: ["solar for farm vadodara", "agriculture solar", "farm solar pump", "PM KUSUM vadodara"] },
  
  { slug: "solar-for-hotel-vadodara", title: "Solar for Hotel Vadodara | Reduce Operating Costs", h1: "Solar Installation for Hotel in Vadodara – Hospitality Power", metaDescription: "🏨 Hotels & resorts save big with solar in Vadodara! Water heating, lighting, AC support. Reduce operating costs, go green. Impress eco-conscious guests!", description: "Solar for hotels & resorts in Vadodara. Water heating, power & AC with solar for hospitality business.", keywords: ["solar for hotel vadodara", "hotel solar system", "resort solar", "hospitality solar"] },

  // Higher Capacity Keywords
  { slug: "15kw-solar-system-vadodara", title: "15kW Solar System Vadodara | Large Villa & Shop", h1: "15kW Solar System Price in Vadodara – Large Scale Power", metaDescription: "💪 15kW solar powerhouse in Vadodara! Perfect for large villas & shops. 1800-2100 units/month. Net metering, quick ROI. Get custom commercial quote!", description: "15kW solar system in Vadodara. Ideal for large homes, villas & small commercial units. Price with subsidy.", keywords: ["15kW solar system vadodara", "15kW solar price", "large villa solar", "commercial 15kw"] },
  
  { slug: "20kw-solar-system-vadodara", title: "20kW Solar System Vadodara | Commercial Power", h1: "20kW Solar System Price in Vadodara – Medium Business", metaDescription: "🏢 20kW commercial solar in Vadodara! For showrooms, offices, small factories. 2400-2800 units generation. Net metering + fast payback. Quote now!", description: "20kW solar system in Vadodara for commercial establishments. Complete installation with net metering.", keywords: ["20kW solar system vadodara", "20kW commercial solar", "office solar 20kw", "showroom solar"] },
  
  { slug: "25kw-solar-system-vadodara", title: "25kW Solar System Vadodara | Business Power Plant", h1: "25kW Solar System Price in Vadodara – Business Solutions", metaDescription: "⚡ 25kW solar plant for serious businesses in Vadodara! 3000+ units/month. Quick ROI, 80% depreciation. EPC project management. Industrial quote!", description: "25kW solar plant in Vadodara for medium businesses. EPC installation with government subsidy benefits.", keywords: ["25kW solar system vadodara", "25kW solar plant", "medium business solar", "commercial solar 25kw"] },
  
  { slug: "50kw-solar-system-vadodara", title: "50kW Solar System Vadodara | Industrial Power", h1: "50kW Solar Power Plant in Vadodara – Factory Solutions", metaDescription: "🏭 50kW industrial solar in Vadodara! For factories & warehouses. 6000+ units/month. 3-4 year payback, 80% depreciation. EPC turnkey. Get industrial quote!", description: "50kW solar power plant in Vadodara. Industrial solar installation for factories & warehouses.", keywords: ["50kW solar system vadodara", "50kW industrial solar", "factory solar plant", "warehouse solar power"] },
  
  { slug: "100kw-solar-system-vadodara", title: "100kW Solar System Vadodara | Mega Power Plant", h1: "100kW Solar Power Plant in Vadodara – Large Industrial", metaDescription: "⚡ 100kW mega solar plant in Vadodara! For large industries & commercial complexes. 12,000+ units/month. Massive savings! Turnkey EPC. Get project quote!", description: "100kW solar power plant in Vadodara. Large scale industrial & commercial solar installation.", keywords: ["100kW solar system vadodara", "100kW industrial solar", "mega solar plant", "large scale solar"] },

  // Product Keywords
  { slug: "lithium-battery-solar-vadodara", title: "Lithium Battery Solar Vadodara | 10+ Years Life", h1: "Lithium Battery for Solar in Vadodara – Premium Backup", metaDescription: "🔋 Lithium solar batteries in Vadodara – 10-15 year life, 6000+ cycles! Lightweight, fast charging, no maintenance. LiFePO4 technology. Best for hybrid!", description: "Lithium battery for solar systems in Vadodara. Long life, fast charging & lightweight solar batteries.", keywords: ["lithium battery solar vadodara", "lithium solar battery", "lifepo4 solar battery", "premium solar battery"] },
  
  { slug: "solar-with-battery-backup-vadodara", title: "Solar with Battery Backup Vadodara | Zero Power Cuts", h1: "Solar with Battery Backup in Vadodara – Uninterrupted Power", metaDescription: "⚡ Never face power cuts again! Solar + battery backup in Vadodara. Hybrid systems with lithium batteries. Grid benefits + emergency power. Best of both!", description: "Solar system with battery backup in Vadodara. Uninterrupted power during outages with hybrid solar.", keywords: ["solar with battery backup vadodara", "solar battery backup", "hybrid solar with battery", "uninterrupted solar power"] },

  // Government/Utility Keywords
  { slug: "ugvcl-solar-vadodara", title: "UGVCL Solar Connection Vadodara | Net Metering Help", h1: "UGVCL Solar Connection in Vadodara – Complete Assistance", metaDescription: "📋 UGVCL solar connection made easy! We handle complete net metering application in Vadodara. Paperwork, inspection, approval – all sorted. Get connected fast!", description: "UGVCL solar connection & net metering in Vadodara. Complete assistance for UGVCL solar rooftop application.", keywords: ["UGVCL solar vadodara", "UGVCL net metering", "UGVCL solar connection", "UGVCL application help"] },

  // New pages targeting high-impression uncovered queries
  { slug: "solar-inverter-shop-vadodara", title: "Solar Inverter Shop in Vadodara | Best Brands & Repair", h1: "Solar Inverter Shop in Vadodara – All Brands, Sales & Repair", metaDescription: "⚡ Top solar inverter shop in Vadodara! Luminous, Growatt, SolarEdge, Fronius, Delta inverters. Sales, installation & repair. On-grid, off-grid & hybrid. Visit us or call now!", description: "Best solar inverter shop in Vadodara. Sales, installation & repair of all major inverter brands. On-grid, off-grid & hybrid inverters available.", keywords: ["solar inverter shop vadodara", "inverter shop vadodara", "inverter dealers vadodara", "solar inverter repair vadodara", "best inverter vadodara"] },

  { slug: "luminous-solar-panel-vadodara", title: "Luminous Solar Panels Vadodara | Price & Dealers 2026", h1: "Luminous Solar Panels in Vadodara – Authorized Dealer & Best Price", metaDescription: "🌟 Luminous solar panels in Vadodara at best price! Authorized dealer for NXG, Shakti & Rapid series. Compare vs Tata & Waaree. Get quotes + subsidy help!", description: "Luminous solar panel dealer in Vadodara. Best price on Luminous NXG, Shakti & Rapid series panels with installation & subsidy assistance.", keywords: ["luminous solar panel vadodara", "luminous solar dealer vadodara", "luminous NXG panel price", "luminous solar panel price 2026"] },

  { slug: "solar-panel-loan-vadodara", title: "Solar Panel Loan in Vadodara | EMI from ₹1,500/month", h1: "Solar Panel Loan in Vadodara – Easy EMI & Zero-Cost Finance Options", metaDescription: "💳 Solar loan in Vadodara starting at ₹1,500/month! Zero down payment options, SBI & HDFC approved. Cover cost after subsidy with easy EMI. Apply in 24 hours!", description: "Solar panel loan & EMI options in Vadodara. SBI, HDFC & NBFC approved solar loans with zero down payment. Easy EMI starting ₹1,500/month.", keywords: ["solar panel loan vadodara", "solar loan vadodara", "solar EMI vadodara", "solar financing vadodara", "solar panel on EMI"] },
];

// Master keyword map by business slug
export const businessKeywords: Record<string, KeywordConfig[]> = {
  "solar-installation": solarKeywords,
};

// Get keyword config by slug (overloaded function)
export function getKeywordBySlug(keywordSlug: string): KeywordConfig | undefined;
export function getKeywordBySlug(businessSlug: string, keywordSlug: string): KeywordConfig | undefined;
export function getKeywordBySlug(arg1: string, arg2?: string): KeywordConfig | undefined {
  if (arg2 === undefined) {
    return solarKeywords.find(k => k.slug === arg1);
  }
  const keywords = businessKeywords[arg1];
  if (!keywords) return undefined;
  return keywords.find(k => k.slug === arg2);
}

// Get all keyword slugs for a business
export function getKeywordSlugs(businessSlug: string): string[] {
  const keywords = businessKeywords[businessSlug];
  if (!keywords) return [];
  return keywords.map(k => k.slug);
}
